name: 'doo some test'
on: 
  push:
    branches: [main]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - env:
          HUB: ${{toJSON(github)}}
        run: echo $HUB
      - run: echo ${{github.ref}}
