name: 'ssdoo some test'
on: 
  push:
    tags: 
      - '*'
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - env:
          HUB: ${{toJSON(github)}}
        run: echo $HUB
      - run: echo ${GITHUB_REF/refs\/tags\//}
